#!/bin/sh

# 获取当前脚本所在位置
# 兼容 sh，判断 BASH_SOURCE 是否存在
if [ -n "$BASH_SOURCE" ]; then
    SCRIPT_FILE=${BASH_SOURCE[0]}
else
    # 处理 sh 的情况，使用 $0 作为脚本名称
    # 这里有例外，如果通过 source 或者 . 执行，这里有问题
    # 目前只能这样写
    SCRIPT_FILE=$0
fi

BASE_DIR=$(dirname "$SCRIPT_FILE")
BASE_DIR=$(cd "$BASE_DIR" && pwd)

run_vim () {
    vim_root=$BASE_DIR
    VIMRUNTIME=$(find "$vim_root/share/vim" -mindepth 1 -maxdepth 1 -type d -name 'vim*' | head -n1)
    export VIMRUNTIME
    "$vim_root/bin/vim" -u "$vim_root/vimrc_custom.vim" "$@"
}

run_vim "$@"

unset SCRIPT_FILE
unset BASE_DIR
unset VIMRUNTIME
unset vim_root
