#!/bin/bash

# 获取当前脚本所在位置
SCRIPT_FILE=$(readlink -f "${BASH_SOURCE[0]}")
BASE_DIR=$(dirname "$SCRIPT_FILE")
readonly SCRIPT_FILE
readonly BASE_DIR

NMAP_ROOT=$BASE_DIR

SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")

run_nmap_tool () {

    LD_LIBRARY_PATH=$NMAP_ROOT/lib64 "$NMAP_ROOT/bin/$SCRIPT_NAME" "$@"

}

show_help () {
    echo
    find "$NMAP_ROOT" -maxdepth 1 -type l -name '*'
    echo
    echo 'Symbolic link created successfully.'
    echo
}

create_symbolic_link () {
    ln -sfr "$SCRIPT_FILE" "$NMAP_ROOT/ncat"
    ln -sfr "$SCRIPT_FILE" "$NMAP_ROOT/ndiff"
    ln -sfr "$SCRIPT_FILE" "$NMAP_ROOT/nmap"
    ln -sfr "$SCRIPT_FILE" "$NMAP_ROOT/nping"
    show_help
}



case "${SCRIPT_NAME}" in
    'ncat' | 'ndiff' | 'nmap' | 'nping')
        run_nmap_tool "$@"
    ;;
    *)
        create_symbolic_link
    ;;
esac
